export const GET_ALL_EMPLOYEES_REQUEST = 'GET_ALL_EMPLOYEES_REQUEST';
export const GET_ALL_EMPLOYEES_SUCCESS = 'GET_ALL_EMPLOYEES_SUCCESS';
export const GET_ALL_EMPLOYEES_FAILURE = 'GET_ALL_EMPLOYEES_FAILURE';

export const SET_NAME = 'SET_NAME';
export const SET_NAME_REQUEST = 'SET_NAME_REQUEST';
export const SET_NAME_SUCCESS = 'SET_NAME_SUCCESS';

