export const GET_ALL_EMPLOYEES_REQUEST = 'GET_ALL_EMPLOYEES_REQUEST';
export const GET_ALL_EMPLOYEES_SUCCESS = 'GET_ALL_EMPLOYEES_SUCCESS';
export const GET_ALL_EMPLOYEES_FAILURE = 'GET_ALL_EMPLOYEES_FAILURE';

export const CREATE_NEW_EMPLOYEE_REQUEST = 'CREATE_NEW_EMPLOYEE_REQUEST';
export const CREATE_NEW_EMPLOYEE_SUCCESS = 'CREATE_NEW_EMPLOYEE_SUCCESS';
export const CREATE_NEW_EMPLOYEE_FAILURE = 'CREATE_NEW_EMPLOYEE_FAILURE';

export const EDIT_EMPLOYEE_REQUEST = 'EDIT_EMPLOYEE_REQUEST';
export const EDIT_EMPLOYEE_SUCCESS = 'EDIT_EMPLOYEE_SUCCESS';
export const EDIT_EMPLOYEE_FAILURE = 'EDIT_EMPLOYEE_FAILURE';

export const SET_NEW_ACTIVE_ROW = 'SET_NEW_ACTIVE_ROW';

export const SET_NAME = 'SET_NAME';
export const SET_NAME_REQUEST = 'SET_NAME_REQUEST';
export const SET_NAME_SUCCESS = 'SET_NAME_SUCCESS';

